package com.silliconpowerinc.tvpop.ui.viewmodels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import androidx.paging.cachedIn
import androidx.paging.filter
import com.silliconpowerinc.tvpop.data.utils.LanguageObserver
import com.silliconpowerinc.tvpop.domain.models.TVShow
import com.silliconpowerinc.tvpop.domain.repositories.AIRepository
import com.silliconpowerinc.tvpop.domain.repositories.TMDBRepository
import com.silliconpowerinc.tvpop.ui.views.details.AIOverviewError
import com.silliconpowerinc.tvpop.ui.views.details.AIOverviewState
import com.silliconpowerinc.tvpop.ui.views.details.DetailsScreenState
import com.silliconpowerinc.tvpop.ui.views.list.components.TVShowListEvent
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.launch
import org.koin.core.annotation.KoinViewModel

/**
 * ViewModel for managing the TV show list and details.
 * It handles the flow of TV show data in accordance with the device's language.
 *
 * @property tmdbRepository Repository for fetching TV shows from TMDB.
 * @param languageObserver Observer for tracking device language changes.
 */
@KoinViewModel
class TVShowsViewModel(
    private val tmdbRepository: TMDBRepository,
    private val aiRepository: AIRepository,
    languageObserver: LanguageObserver
) : ViewModel() {
    /**
     * Handles events from the TV show list UI.
     *
     * @param event The event to be processed.
     */
    fun onEvent(event: TVShowListEvent) {}

    private val _uiState = MutableStateFlow(DetailsScreenState(AIOverviewState.Loading))
    val uiState = _uiState.asStateFlow()

    val languageTagFlow = languageObserver.languageTagFlow

    /**
     * The flow of paginated TV show data, provided in the device's current language.
     * Duplicate entries across pages are filtered out, and the data is cached in the [viewModelScope].
     */
    @OptIn(ExperimentalCoroutinesApi::class)
    val tvShowsFlow = languageTagFlow.flatMapLatest { language ->
        tmdbRepository.getTVShowsFlow(language = language).map { pagingData ->
            val receivedIds = mutableSetOf<Int>()
            // Apply a filter to remove duplicate entries returned by the API
            // (I've found duplicates across pages 1 and 2 with IDs 4604 and 66732)
            pagingData.filter { tvShow ->
                val isNew = tvShow.id !in receivedIds
                // Add new IDs to the set. If the ID has already been seen, it gets ignored.
                if (isNew) receivedIds.add(tvShow.id)
                // If isNew, include it in the flow (true); else, filter it out (false).
                return@filter isNew
            }
        }
    }.cachedIn(viewModelScope)

    /**
     * Retrieves a specific [TVShow] by its [id] from the repository if it exists.
     *
     * @param id The ID of the TV show.
     * @return The [TVShow] if found, or null otherwise.
     */
    fun getTVShow(id: Int): TVShow? = tmdbRepository.getTVShow(id)

    /**
     * Loads the AI-generated overview for a TV show with the given [tvShowId].
     * If the overview is already cached, it will be returned immediately. Otherwise,
     * it will be generated by the AI service and cached.
     *
     * @param tvShowId The ID of the TV show for which to load the AI overview.
     */
    fun loadAIOverview(tvShowId: Int) {
        _uiState.value = _uiState.value.copy(aiOverviewState = AIOverviewState.Loading)
        val currentLanguage = languageTagFlow.value

        val tvShow = tmdbRepository.getTVShow(tvShowId)
        if (tvShow == null) {
            _uiState.value = _uiState.value.copy(
                aiOverviewState = AIOverviewState.Error(
                    errorType = AIOverviewError.TVShowNotFound,
                )
            )
            return
        }

        if (tvShow.aiOverview != null && tvShow.aiOverviewLanguage == currentLanguage) {
            _uiState.value =
                _uiState.value.copy(aiOverviewState = AIOverviewState.Success(tvShow.aiOverview))
        } else {
            viewModelScope.launch {
                try {
                    val aiOverview =
                        aiRepository.generateAIOverview(tvShow = tvShow, language = currentLanguage)

                    tmdbRepository.updateTVShowAIOverview(
                        id = tvShowId,
                        aiOverview = aiOverview,
                        language = currentLanguage
                    )

                    _uiState.value =
                        _uiState.value.copy(aiOverviewState = AIOverviewState.Success(aiOverview))
                } catch (e: Exception) {
                    val message =
                        if (e.localizedMessage.isNullOrBlank()) null else e.localizedMessage
                    _uiState.value =
                        _uiState.value.copy(aiOverviewState = AIOverviewState.Error(message = message))
                }
            }
        }
    }
}
